### PR TITLE
Create 2_Maximum_Subarray.cpp

### PR DESCRIPTION
**Pull request by siddharthsinghvats**
Problem 2 in C++

### CODE REVIEW

**Comment by Rushijaviya** [comment]
you are solving on GFG or LeetCode? can you share the link to this question?

**Comment by siddharthsinghvats** [comment]
> you are solving on GFG or LeetCode? can you share the link to this question?

https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s4231/1/
This one gfg
other one leetcode

**Comment by Rushijaviya** [comment]
have you modified the input parameters? the default input parameter is only one which is an array.

**Comment by siddharthsinghvats** [comment]
> have you modified the input parameters? the default input parameter is only one which is an array.

i guess no

**Comment by Rushijaviya** [comment]
can you share the submission link of solution here?

**Comment by siddharthsinghvats** [comment]
> can you share the submission link of solution here?

https://leetcode.com/submissions/detail/616959123/

**Comment by Rushijaviya** [comment]
your code doesn't match the submission code. But, it's fine. I will make the needed changes.

**Pull request merged**
